repos:
  - repo: local
    hooks:
      - id: clang-format
        name: Clang Format
        entry: clang-format -i --style=file
        language: system
        files: \.(c|cpp|h|hpp|cc|cxx)$
        require_serial: true

      - id: utf8-check
        name: Check UTF-8 without BOM / ASCII
        entry: python hooks/utf8_check.py
        language: system
        stages: [pre-commit]
        types: [text]
